---
language: python
python: "3.8"

env:
- A=true
- B=false

sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - mv "$PWD" "${PWD%/*}/users"
  # Install ansible
  - pip install ansible molecule docker testinfra pytest pytest-xdist

  # Check ansible version
  - ansible --version

  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
