---
- name: Converge
  hosts: all
  tasks:
    - name: "Include users"
      include_role:
        name: "users"
      vars:
        users_groups:
          - docker
        users:
          - name: test1
            groups: 
              - sudo
              - docker
            ssh_keys: 
              - test1
              - test2
          - name: app
            ssh_keys:
              - test2
        users_root_ssh_keys: 
          - test1