---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: ${MOLECULE_DISTRIBUTION:-debian10}
    image: "nekeal/${MOLECULE_DISTRO:-debian10}-ansible-systemd:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    tmpfs:
      - /var/lib/docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: testinfra
